'use client'

import { AnimatePresence, motion } from 'framer-motion'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { PageWrapper } from '@/components/page-wrapper'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

function handleExitComplete() {
  if (typeof window !== 'undefined') {
    window.scrollTo({ top: 0 })
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div class='p-4' style={{background: "pink"}}>
          <ul class='flex space-x-4'>
            <Link href="/">HOME</Link>
            <Link href="/route-first">ROUTE-FIRST</Link>
          </ul>
        </div>
        <div>
          <h3>DOWN HERE IS THE ROUTER</h3>
          <div>
            {/* this is not working */}
            {/* <PageWrapper>
              {children}
            </PageWrapper> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
